name: "Get project field ID from name"
author: "Christian Toney"
description: "Convert a project field name to an ID. You can use a personal access token (PAT) or GitHub app."
inputs:

  # Project metadata
  github-project-id:
    description: "The ID of the project that has the field."
    required: true
  github-project-field-name:
    description: "The name of the field that you want to get the ID of."
    required: true

  # Authentication inputs for GitHub app
  github-app-id:
    description: "The ID of your GitHub app. Required if a personal access token is not provided."
    required: false
  github-app-private-key:
    description: "A private key of your GitHub app. Required if a personal access token is not provided."
    required: false
  github-app-installation-id:
    description: "The installation ID of the GitHub app. You can get this from checking the URL after hitting configure at https://github.com/{USER or ORGANIZATION}/{REPOSITORY}/settings/installations."
    required: false
  
  # Authentication inputs for personal access token
  github-personal-access-token:
    description: "The access token of the GitHub account. Required if GitHub app authentication inputs are not provided."
    required: false

runs:
  using: "node20"
  main: "dist/index.js"
